spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:devdb
    username: dev
    password:
  jpa:
    open-in-view: false
  jackson:
    default-property-inclusion: NON_EMPTY
    deserialization.fail-on-unknown-properties: false
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false